"""Parallax Tool Dispatcher & In-Process Typed Dispatch Boundary.

Implements the Cognitive-Executive API boundary. The Cognitive Layer (LLM reasoning loop)
uses this dispatcher to send structured ToolCallPayload objects to an in-process Executive
Engine Process (or an optional remote HTTP endpoint).

Algorithmic Complexity:
    - Serialization & Dispatch: O(N) payload size.
    - Network I/O: Asynchronous non-blocking await.
"""

from __future__ import annotations

import logging

from src.engine.executor import ExecutiveEngineProcess
from src.reasoning.schemas import ObservationPayload, ToolCallPayload

logger = logging.getLogger(__name__)


class ParallaxToolDispatcher:
    """Asynchronous boundary gateway for Cognitive-Executive Separation.

    Dispatches tool execution requests generated by the LLM reasoning process across
    an in-process typed interface boundary, guaranteeing that the reasoning process cannot
    directly invoke OS, file system, or network resources.

    Attributes:
        executor: Attached ExecutiveEngineProcess for in-process execution, or None if remote HTTP.
        endpoint_url: Optional remote URL/endpoint for HTTP server.
    """

    def __init__(
        self,
        executor: ExecutiveEngineProcess | None = None,
        endpoint_url: str | None = None,
    ) -> None:
        """Initialize the Parallax Tool Dispatcher.

        Args:
            executor: Optional in-memory ExecutiveEngineProcess instance.
            endpoint_url: Optional remote HTTP service endpoint URL.
        """
        self.executor = executor or ExecutiveEngineProcess()
        self.endpoint_url = endpoint_url
        logger.info(
            "ParallaxToolDispatcher initialized (remote_endpoint=%s, local_executor=%s)",
            endpoint_url,
            self.executor is not None,
        )

    async def dispatch_tool_call(self, payload: ToolCallPayload) -> ObservationPayload:
        """Dispatch a validated tool call payload across the Parallax boundary.

        If a remote endpoint URL is configured, sends an HTTP request asynchronously.
        Otherwise, routes to the local in-process ExecutiveEngineProcess handler.

        Args:
            payload: Validated ToolCallPayload object.

        Returns:
            Structured ObservationPayload containing execution status and outputs.
        """
        logger.debug("Dispatching tool call '%s' (call_id=%s)", payload.tool_name, payload.call_id)

        if self.endpoint_url:
            return await self._dispatch_remote_http(payload)
        else:
            return await self.executor.execute_tool_call(payload)

    async def _dispatch_remote_http(self, payload: ToolCallPayload) -> ObservationPayload:
        """Dispatch tool call to remote endpoint via aiohttp.

        Args:
            payload: Validated ToolCallPayload object.

        Returns:
            ObservationPayload response.
        """
        try:
            import aiohttp

            async with (
                aiohttp.ClientSession() as session,
                session.post(
                    f"{self.endpoint_url}/api/v1/execute",
                    json=payload.model_dump(),
                    timeout=aiohttp.ClientTimeout(total=payload.timeout_seconds),
                ) as resp,
            ):
                if resp.status == 200:
                    data = await resp.json()
                    return ObservationPayload.model_validate(data)
                else:
                    error_text = await resp.text()
                    return ObservationPayload(
                        call_id=payload.call_id,
                        success=False,
                        output_data={},
                        error_message=f"HTTP boundary error ({resp.status}): {error_text}",
                        execution_time_ms=0.0,
                    )
        except Exception as exc:  # noqa: BLE001
            logger.error("Remote boundary dispatch error: %s", exc)
            return ObservationPayload(
                call_id=payload.call_id,
                success=False,
                output_data={},
                error_message=f"Parallax remote dispatch exception: {exc!s}",
                execution_time_ms=0.0,
            )


__all__ = ["ParallaxToolDispatcher"]
